### ISSUE TITLE
Type Error in PostNewChatInput

### ISSUE THREAD

**Issue by guillaume-miara** [unipile/unipile-node-sdk#3]
See [https://github.com/unipile/unipile-node-sdk/blob/develop/src/types/input/input-messaging.ts#L58](here), I think we'd want
`attendees_ids: string[];`

FYI I didn't have the permissions to contribute by pushing a fix for this. Not sure if it's intentional.

**Comment by svadhis** [comment]
Hi Guillaume,

Thanks for pointing this out! We've fixed the issue and it will be included in the upcoming release. 

Regarding the permissions, it is intentional to control changes through pull requests for better tracking. Feel free to submit one in the future!
