### ISSUE TITLE
only_unreads option is ignored when calling getAllChats

### ISSUE THREAD

**Issue by jamesdnexa** [unipile/unipile-node-sdk#4]
```
   const response = await client.messaging.getAllChats({
      account_id: from_account,
      only_unreads: true,
      limit:5
    });
```
Result: 5 chats, every one is read.  Changing the option to false gives the exact same 5 chat objects.

Via a CURL request, things workout fine using the unread=true parameter:

```

curl --request GET \
     --url 'https://api1.unipile.com:13111/api/v1/chats?unread=true' \
     --header 'X-API-KEY: <my key>' \
     --header 'accept: application/json'

```

**Comment by svadhis** [comment]
Hi,

Thanks for reporting the issue. The problem has been fixed in version 1.4.3 please notice that you will have to use 'unread' parameter instead of 'only_unreads'.
